---
# tasks file for ambiente
- name: Cria os containers para o blue
  docker_container:
    name: blue
    image: httpd
    state: started
    restart_policy: always
    volumes:
      - /blue:/usr/local/apache2/htdocs/

- name: Cria os containers para o green
  docker_container:
    name: green
    image: httpd
    state: started
    restart_policy: always
    volumes:
      - /green:/usr/local/apache2/htdocs/
