---
- hosts: all
  tasks: 

    - block: 
        - name: Instala o apache para o Debian
          apt:
            name: apache2
            state: present

        - name: Iniciar o servico do Apache
          service: 
            name: apache2
            state: started

      when: ansible_distribution == 'Ubuntu'


    - block: 
        - name: Instala o pache para RedHat
          yum: 
            name: httpd
            state: present

        - name: Iniciar o servico do Httpd 
          service:
            name: httpd
            state: started 
          
      when: ansible_distribution == 'CentOS'

    - name: Copia conteudo do portal DEXTER
      copy: 
        src: index.html
        dest: /var/www/html/index.html 
